MENG_CPPFLAGS_webrtc/modules/audio_coding/codecs/ilbc/ += \
	-Imediaengine/webrtc/modules/audio_coding/codecs/ilbc/interface

MENG_SRCS += \
	webrtc/modules/audio_coding/codecs/ilbc/abs_quant.c \
	webrtc/modules/audio_coding/codecs/ilbc/abs_quant_loop.c \
	webrtc/modules/audio_coding/codecs/ilbc/audio_encoder_ilbc.cc \
	webrtc/modules/audio_coding/codecs/ilbc/augmented_cb_corr.c \
	webrtc/modules/audio_coding/codecs/ilbc/bw_expand.c \
	webrtc/modules/audio_coding/codecs/ilbc/cb_construct.c \
	webrtc/modules/audio_coding/codecs/ilbc/cb_mem_energy.c \
	webrtc/modules/audio_coding/codecs/ilbc/cb_mem_energy_augmentation.c \
	webrtc/modules/audio_coding/codecs/ilbc/cb_mem_energy_calc.c \
	webrtc/modules/audio_coding/codecs/ilbc/cb_search.c \
	webrtc/modules/audio_coding/codecs/ilbc/cb_search_core.c \
	webrtc/modules/audio_coding/codecs/ilbc/cb_update_best_index.c \
	webrtc/modules/audio_coding/codecs/ilbc/chebyshev.c \
	webrtc/modules/audio_coding/codecs/ilbc/comp_corr.c \
	webrtc/modules/audio_coding/codecs/ilbc/constants.c \
	webrtc/modules/audio_coding/codecs/ilbc/create_augmented_vec.c \
	webrtc/modules/audio_coding/codecs/ilbc/decode.c \
	webrtc/modules/audio_coding/codecs/ilbc/decode_residual.c \
	webrtc/modules/audio_coding/codecs/ilbc/decoder_interpolate_lsf.c \
	webrtc/modules/audio_coding/codecs/ilbc/do_plc.c \
	webrtc/modules/audio_coding/codecs/ilbc/encode.c \
	webrtc/modules/audio_coding/codecs/ilbc/energy_inverse.c \
	webrtc/modules/audio_coding/codecs/ilbc/enh_upsample.c \
	webrtc/modules/audio_coding/codecs/ilbc/enhancer.c \
	webrtc/modules/audio_coding/codecs/ilbc/enhancer_interface.c \
	webrtc/modules/audio_coding/codecs/ilbc/filtered_cb_vecs.c \
	webrtc/modules/audio_coding/codecs/ilbc/frame_classify.c \
	webrtc/modules/audio_coding/codecs/ilbc/gain_dequant.c \
	webrtc/modules/audio_coding/codecs/ilbc/gain_quant.c \
	webrtc/modules/audio_coding/codecs/ilbc/get_cd_vec.c \
	webrtc/modules/audio_coding/codecs/ilbc/get_lsp_poly.c \
	webrtc/modules/audio_coding/codecs/ilbc/get_sync_seq.c \
	webrtc/modules/audio_coding/codecs/ilbc/hp_input.c \
	webrtc/modules/audio_coding/codecs/ilbc/hp_output.c \
	webrtc/modules/audio_coding/codecs/ilbc/ilbc.c \
	webrtc/modules/audio_coding/codecs/ilbc/index_conv_dec.c \
	webrtc/modules/audio_coding/codecs/ilbc/index_conv_enc.c \
	webrtc/modules/audio_coding/codecs/ilbc/init_decode.c \
	webrtc/modules/audio_coding/codecs/ilbc/init_encode.c \
	webrtc/modules/audio_coding/codecs/ilbc/interpolate.c \
	webrtc/modules/audio_coding/codecs/ilbc/interpolate_samples.c \
	webrtc/modules/audio_coding/codecs/ilbc/lpc_encode.c \
	webrtc/modules/audio_coding/codecs/ilbc/lsf_check.c \
	webrtc/modules/audio_coding/codecs/ilbc/lsf_interpolate_to_poly_dec.c \
	webrtc/modules/audio_coding/codecs/ilbc/lsf_interpolate_to_poly_enc.c \
	webrtc/modules/audio_coding/codecs/ilbc/lsf_to_lsp.c \
	webrtc/modules/audio_coding/codecs/ilbc/lsf_to_poly.c \
	webrtc/modules/audio_coding/codecs/ilbc/lsp_to_lsf.c \
	webrtc/modules/audio_coding/codecs/ilbc/my_corr.c \
	webrtc/modules/audio_coding/codecs/ilbc/nearest_neighbor.c \
	webrtc/modules/audio_coding/codecs/ilbc/pack_bits.c \
	webrtc/modules/audio_coding/codecs/ilbc/poly_to_lsf.c \
	webrtc/modules/audio_coding/codecs/ilbc/poly_to_lsp.c \
	webrtc/modules/audio_coding/codecs/ilbc/refiner.c \
	webrtc/modules/audio_coding/codecs/ilbc/simple_interpolate_lsf.c \
	webrtc/modules/audio_coding/codecs/ilbc/simple_lpc_analysis.c \
	webrtc/modules/audio_coding/codecs/ilbc/simple_lsf_dequant.c \
	webrtc/modules/audio_coding/codecs/ilbc/simple_lsf_quant.c \
	webrtc/modules/audio_coding/codecs/ilbc/smooth.c \
	webrtc/modules/audio_coding/codecs/ilbc/smooth_out_data.c \
	webrtc/modules/audio_coding/codecs/ilbc/sort_sq.c \
	webrtc/modules/audio_coding/codecs/ilbc/split_vq.c \
	webrtc/modules/audio_coding/codecs/ilbc/state_construct.c \
	webrtc/modules/audio_coding/codecs/ilbc/state_search.c \
	webrtc/modules/audio_coding/codecs/ilbc/swap_bytes.c \
	webrtc/modules/audio_coding/codecs/ilbc/unpack_bits.c \
	webrtc/modules/audio_coding/codecs/ilbc/vq3.c \
	webrtc/modules/audio_coding/codecs/ilbc/vq4.c \
	webrtc/modules/audio_coding/codecs/ilbc/window32_w32.c \
	webrtc/modules/audio_coding/codecs/ilbc/xcorr_coef.c

