/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_waz_avs_VideoCapturer */

#ifndef _Included_com_waz_avs_VideoCapturer
#define _Included_com_waz_avs_VideoCapturer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_waz_avs_VideoCapturer
 * Method:    handleCameraFrame
 * Signature: (II[BIJ)V
 */
JNIEXPORT void JNICALL Java_com_waz_avs_VideoCapturer_handleCameraFrame
  (JNIEnv *, jclass, jint, jint, jbyteArray, jint, jlong);

JNIEXPORT void JNICALL Java_com_waz_avs_VideoCapturer_handleCameraFrame2
  (JNIEnv *, jclass, jint, jint,
   jobject, jint,
   jobject, jint,
   jobject, jint,
   jint, jlong);
	
#ifdef __cplusplus
}
#endif
#endif
